# Generated by Django 4.1.7 on 2023-03-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_order_car_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
    ]
