# Generated by Django 4.1.7 on 2023-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_car_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mileage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
