# Generated by Django 4.1.7 on 2023-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_customer_options_alter_orderrow_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='customers', to='service.car'),
        ),
    ]
