# Generated by Django 4.1.7 on 2023-04-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_customer_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderRow',
            new_name='OrderItem',
        ),
        migrations.RemoveConstraint(
            model_name='car',
            name='unique_VIN',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='VIN',
            new_name='vin',
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('vin',), name='unique_vin'),
        ),
    ]
